### ISSUE TITLE
Support Docker Image for use in CI Systems such as Jenkins. 

### ISSUE THREAD

**Issue by krmeda** [hsdp/python-cf-api#2]
Having a Docker image with the release already installed helps to run in CI Systems such as Jenkins or Concourse. Concourse CI has a resource, but does not really support scenarios where CF Services might need to be provisioned, etc. 

The second use case would be to use the Docker Image to run CF tasks or Iron.io jobs for performing operations activities

**Comment by adamjaso** [comment]
In version 1.0.0, I've providing a Dockerfile that should get you started with running `cf_api` in Docker. I don't want to manage a public Docker image at this time.
